#!/usr/bin/env python2.7

from __future__ import division, print_function
#from mbauth.pitch import frequencies, iterpitches
from pitch import frequencies, iterpitches

FRAMERATE = 11025 #44100
BITDEPTH = 8
AMPLITUDE = 100

import shutil
import os
import wave
import math
import struct

folder = os.path.join(os.path.dirname(__file__), "samples")

if os.path.exists(folder):
    shutil.rmtree(folder)
os.mkdir(folder)

for pitch in iterpitches():
    f = wave.open(os.path.join(folder, pitch + ".wav"), "wb")
    try:
        f.setnchannels(1)
        f.setsampwidth(BITDEPTH // 8)
        f.setframerate(FRAMERATE)
        frequency = frequencies[pitch] 
        periods = 2
    
        for step in range(FRAMERATE):  # 1 seconds
            time = step / float(FRAMERATE)
            value = int(AMPLITUDE * math.sin(2.0 * math.pi * frequency * time))
            byte = struct.pack("b", value)
            assert len(byte) == 1
            f.writeframes(byte)
    finally:
        f.close()
        print(pitch, "done")
